server:
  port: 8090

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  main:
    allow-circular-references: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    druid:
      driver-class-name: ${erp.datasource.driver-class-name}
      url: jdbc:mysql://${erp.datasource.host}:${erp.datasource.port}/${erp.datasource.database}?serverTimezone=Europe/London&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${erp.datasource.username}
      password: ${erp.datasource.password}

  mail:
    host: ${erp.mail.host}
    port: ${erp.mail.port}
    username: ${erp.mail.username}
    password: ${erp.mail.password}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


  redis:
    host: ${erp.redis.host}
    port: ${erp.redis.port}
    password: ${erp.redis.password}


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.erp.entity
  configuration:
    # camel naming
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      erp:
        mapper: debug
        service: info
        controller: info

erp:
  jwt:
    # secret key for jwt generation
    admin-secret-key: adminkey
    # jwt expiry time
    admin-ttl: 7200000
    # front-end passed token name
    admin-token-name: token
#    user-secret-key: userkey
#    user-ttl: 7200000
#    user-token-name: authentication

  alioss:
    endpoint: ${erp.alioss.endpoint}
    access-key-id: ${erp.alioss.access-key-id}
    access-key-secret: ${erp.alioss.access-key-secret}
    bucket-name: ${erp.alioss.bucket-name}


llm:
  base-url: ${erp.llm.base-url}
  model: ${erp.llm.model}
  api-key: ${erp.llm.api-key}
  timeout-ms: 12000